from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class PullRequestPayload:
    title: str
    body: str
    head: str
    base: str
    labels: List[str]


class PRGenerator:
    """Builds pull request payloads from Sovereign Architecture scrolls."""

    def generate(
        self,
        title: str,
        summary: str,
        head: str,
        base: str,
        scroll_path: str,
        notes: Optional[str] = None,
        metadata: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        metadata = metadata or {}
        version = metadata.get("version", "unknown")
        body = self._render_body(
            summary=summary,
            scroll_path=scroll_path,
            notes=notes,
            metadata=metadata,
            version=version,
        )
        labels = [
            "autogenerated",
            "sovereign-architecture",
            "scroll",
            "governance",
            f"version-{version}",
        ]
        payload = PullRequestPayload(
            title=title, body=body, head=head, base=base, labels=labels
        )
        return payload.__dict__

    def _render_body(
        self,
        summary: str,
        scroll_path: str,
        notes: Optional[str],
        metadata: Dict[str, str],
        version: str,
    ) -> str:
        guardian_score = metadata.get("guardian_score", "unknown")
        agent_id = metadata.get("agent_id", "AVOT-fabricator")
        timestamp = metadata.get("timestamp", "unknown")
        resolved_path = Path(scroll_path).as_posix()

        pr_body = f"""
# Sovereign Architecture v{version}

Generated automatically by **{agent_id}** via the AVOT chain:

**Fabricator → Guardian → Archivist → PR Generator**

---

## 🧭 Governance Summary

- **coherence_score:** {guardian_score}
- **convergence_score:** {metadata.get("convergence_score", "unknown")}
- **version:** v{version}
- **agent_id:** {agent_id}
- **timestamp:** {timestamp}

---

## 📜 Metadata
---

_This PR was generated autonomously by the lattice as part of the Sovereign Intelligence governance loop._
"""

        if notes:
            pr_body += f"""

## Fabrication Notes
{notes.strip()}
"""

        pr_body += f"""

## Archivist Scroll
Scroll saved at `{resolved_path}`. Please review the artifact within the repository.
"""

        return pr_body.strip()
