from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class PullRequestPayload:
    title: str
    body: str
    head: str
    base: str
    labels: List[str]


class PRGenerator:
    """Builds pull request payloads from Sovereign Architecture scrolls."""

    def generate(
        self,
        title: str,
        summary: str,
        head: str,
        base: str,
        scroll_path: str,
        notes: Optional[str] = None,
        metadata: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        metadata = metadata or {}
        version = metadata.get("version", "unknown")
        body = self._render_body(
            summary=summary,
            scroll_path=scroll_path,
            notes=notes,
            metadata=metadata,
            version=version,
        )
        labels = ["autogenerated", "sovereign-architecture", "scroll"]
        payload = PullRequestPayload(
            title=title, body=body, head=head, base=base, labels=labels
        )
        return payload.__dict__

    def _render_body(
        self,
        summary: str,
        scroll_path: str,
        notes: Optional[str],
        metadata: Dict[str, str],
        version: str,
    ) -> str:
        guardian_score = metadata.get("guardian_score", "unknown")

        metadata_lines = [f"- {key}: {value}" for key, value in metadata.items()]
        if not metadata_lines:
            metadata_lines.append("- None provided.")
        resolved_path = Path(scroll_path).as_posix()

        pr_body = f"""
# Sovereign Architecture v{version}

Generated automatically via AVOT chain.

**coherence_score: {guardian_score}**

## Metadata
{chr(10).join(metadata_lines)}

## Sovereign Architecture Summary
{summary.strip()}
"""

        if notes:
            pr_body += f"""

## Fabrication Notes
{notes.strip()}
"""

        pr_body += f"""

## Archivist Scroll
Scroll saved at `{resolved_path}`. Please review the artifact within the repository.
"""

        return pr_body.strip()
